/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tec.proyectomatricula;

import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFileChooser;

import tec.proyectomatricula.EmailOpController.EmailSender;
import tec.proyectomatricula.FileController.PDFCreator;

import tec.proyectomatricula.controladores.CursoController;
import tec.proyectomatricula.controladores.EscuelaAreaController;
import tec.proyectomatricula.controladores.PlanEstudiosController;
import tec.proyectomatricula.modelos.Curso;
import tec.proyectomatricula.modelos.EscuelaArea;
import tec.proyectomatricula.modelos.PlanEstudios;

/**
 *
 * @author david    
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        MenuPanel = new javax.swing.JPanel();
        MenuLabel = new javax.swing.JLabel();
        RegCursoMenubutton = new javax.swing.JButton();
        ReqCorrMenuButton = new javax.swing.JButton();
        CreatePlanMenubutton = new javax.swing.JButton();
        RegEscuelaMenubutton = new javax.swing.JButton();
        PDFMenubutton = new javax.swing.JButton();
        RegEscuelaPanel = new javax.swing.JPanel();
        RegEscuelaLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NombreField = new javax.swing.JTextField();
        CodigoField = new javax.swing.JTextField();
        RegistrarEscuelabutton = new javax.swing.JButton();
        LimpiarEscuelabutton = new javax.swing.JButton();
        Escuela_to_menubutton = new javax.swing.JButton();
        RegCursoPanel = new javax.swing.JPanel();
        RegCursosLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NombreCursoField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        RegCursoEscuelaCodigoLabel = new javax.swing.JLabel();
        RegCursoCodField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        RegCursoCredbox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        RegCursoHorasbox = new javax.swing.JComboBox<>();
        RegCursoEscuelabox = new javax.swing.JComboBox<>();
        RegisterCursobutton = new javax.swing.JButton();
        LimpiarCursosbutton = new javax.swing.JButton();
        Cursos_to_Menubutton = new javax.swing.JButton();
        ReqCorrPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ReqCorrEscuelabox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        ReqCorrCodigoCbox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ReqCorrCodReqbox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ReqCorrCursoCorrbox = new javax.swing.JComboBox<>();
        RegReqbutton = new javax.swing.JButton();
        RegCorrbutton = new javax.swing.JButton();
        ReqCorr_to_menubutton = new javax.swing.JButton();
        PlanEstudioPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        PlanEscuelabox = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        PlanCodigoField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        PlanCursoField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        PlanSemestrebox = new javax.swing.JComboBox<>();
        PlanRegbutton = new javax.swing.JButton();
        Planes_to_menubutton = new javax.swing.JButton();
        PlanDiabox = new javax.swing.JComboBox<>();
        PlanAnnobox = new javax.swing.JComboBox<>();
        PlanMesbox = new javax.swing.JComboBox<>();
        PDFPanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        PDFPlanbox = new javax.swing.JComboBox<>();
        GenPDFbutton = new javax.swing.JButton();
        PDF_to_menubutton = new javax.swing.JButton();
        Correobutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        MenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuLabel.setText("MENU");

        RegCursoMenubutton.setText("Registrar Curso");
        RegCursoMenubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegCursoMenubuttonActionPerformed(evt);
            }
        });

        ReqCorrMenuButton.setText("Registrar Requisitos y Correquisitos");
        ReqCorrMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReqCorrMenuButtonActionPerformed(evt);
            }
        });

        CreatePlanMenubutton.setText("Crear Plan de Estudio ");
        CreatePlanMenubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePlanMenubuttonActionPerformed(evt);
            }
        });

        RegEscuelaMenubutton.setText("Registrar Escuela");
        RegEscuelaMenubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegEscuelaMenubuttonActionPerformed(evt);
            }
        });

        PDFMenubutton.setText("Generar PDF");
        PDFMenubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDFMenubuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegCursoMenubutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegEscuelaMenubutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MenuLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(PDFMenubutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CreatePlanMenubutton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ReqCorrMenuButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(MenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(RegEscuelaMenubutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RegCursoMenubutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ReqCorrMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CreatePlanMenubutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PDFMenubutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        RegEscuelaLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        RegEscuelaLabel.setText("Registro de Escuela o Área Académica");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Código:");

        NombreField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        CodigoField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        RegistrarEscuelabutton.setText("Registrar");
        RegistrarEscuelabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarEscuelabuttonActionPerformed(evt);
            }
        });

        LimpiarEscuelabutton.setText("Limpiar campos");
        LimpiarEscuelabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarEscuelabuttonActionPerformed(evt);
            }
        });

        Escuela_to_menubutton.setText("Volver");
        Escuela_to_menubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Escuela_to_menubuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegEscuelaPanelLayout = new javax.swing.GroupLayout(RegEscuelaPanel);
        RegEscuelaPanel.setLayout(RegEscuelaPanelLayout);
        RegEscuelaPanelLayout.setHorizontalGroup(
            RegEscuelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegEscuelaPanelLayout.createSequentialGroup()
                .addGroup(RegEscuelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegEscuelaPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(RegEscuelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(RegEscuelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CodigoField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(RegEscuelaPanelLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(RegistrarEscuelabutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(LimpiarEscuelabutton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegEscuelaPanelLayout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(RegEscuelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegEscuelaPanelLayout.createSequentialGroup()
                        .addComponent(RegEscuelaLabel)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegEscuelaPanelLayout.createSequentialGroup()
                        .addComponent(Escuela_to_menubutton)
                        .addGap(260, 260, 260))))
        );
        RegEscuelaPanelLayout.setVerticalGroup(
            RegEscuelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegEscuelaPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(RegEscuelaLabel)
                .addGap(47, 47, 47)
                .addGroup(RegEscuelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(RegEscuelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CodigoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(RegEscuelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarEscuelabutton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LimpiarEscuelabutton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(Escuela_to_menubutton)
                .addGap(33, 33, 33))
        );

        RegCursosLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        RegCursosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegCursosLabel.setText("Registro de Cursos");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Escuela propietaria del curso:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nombre del curso:");

        NombreCursoField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NombreCursoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreCursoFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Código del Curso:");

        RegCursoEscuelaCodigoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RegCursoEscuelaCodigoLabel.setText(" ");

        RegCursoCodField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Créditos:");

        RegCursoCredbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Horas Lectivas:");

        RegCursoHorasbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        RegCursoEscuelabox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        RegCursoEscuelabox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RegCursoEscuelaboxItemStateChanged(evt);
            }
        });

        RegisterCursobutton.setText("Registrar");
        RegisterCursobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterCursobuttonActionPerformed(evt);
            }
        });

        LimpiarCursosbutton.setText("Limpiar Campos");
        LimpiarCursosbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarCursosbuttonActionPerformed(evt);
            }
        });

        Cursos_to_Menubutton.setText("volver");
        Cursos_to_Menubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cursos_to_MenubuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegCursoPanelLayout = new javax.swing.GroupLayout(RegCursoPanel);
        RegCursoPanel.setLayout(RegCursoPanelLayout);
        RegCursoPanelLayout.setHorizontalGroup(
            RegCursoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegCursoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegCursosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
            .addGroup(RegCursoPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(RegCursoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegCursoPanelLayout.createSequentialGroup()
                        .addGroup(RegCursoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegCursoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegCursoPanelLayout.createSequentialGroup()
                                .addGroup(RegCursoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(RegCursoPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(RegisterCursobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(RegCursoPanelLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                        .addComponent(RegCursoEscuelaCodigoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)))
                        .addGroup(RegCursoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NombreCursoField, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(RegCursoCodField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegCursoCredbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegCursoHorasbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegCursoEscuelabox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(RegCursoPanelLayout.createSequentialGroup()
                                .addComponent(LimpiarCursosbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Cursos_to_Menubutton)))
                        .addGap(125, 125, 125))
                    .addGroup(RegCursoPanelLayout.createSequentialGroup()
                        .addGroup(RegCursoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegCursoPanelLayout.createSequentialGroup()
                                .addGroup(RegCursoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 375, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        RegCursoPanelLayout.setVerticalGroup(
            RegCursoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegCursoPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(RegCursosLabel)
                .addGap(32, 32, 32)
                .addGroup(RegCursoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(RegCursoEscuelabox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(RegCursoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NombreCursoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(RegCursoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(RegCursoEscuelaCodigoLabel)
                    .addComponent(RegCursoCodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(RegCursoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(RegCursoCredbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(RegCursoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegCursoPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel7))
                    .addGroup(RegCursoPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(RegCursoHorasbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(RegCursoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LimpiarCursosbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterCursobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cursos_to_Menubutton))
                .addGap(27, 27, 27))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Asignar Requisitos y Correquisitos a un curso");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Escuela/Área Propietaria del curso:");

        ReqCorrEscuelabox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ReqCorrEscuelabox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ReqCorrEscuelaboxItemStateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Código de curso:");

        ReqCorrCodigoCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Requisitos de curso:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Código de curso:");

        ReqCorrCodReqbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Correquisitos de curso:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Código de curso:");

        ReqCorrCursoCorrbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        RegReqbutton.setText("Registrar Requisito");
        RegReqbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegReqbuttonActionPerformed(evt);
            }
        });

        RegCorrbutton.setText("Registrar Correquisito");
        RegCorrbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegCorrbuttonActionPerformed(evt);
            }
        });

        ReqCorr_to_menubutton.setText("volver");
        ReqCorr_to_menubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReqCorr_to_menubuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReqCorrPanelLayout = new javax.swing.GroupLayout(ReqCorrPanel);
        ReqCorrPanel.setLayout(ReqCorrPanelLayout);
        ReqCorrPanelLayout.setHorizontalGroup(
            ReqCorrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReqCorrPanelLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(77, 77, 77))
            .addGroup(ReqCorrPanelLayout.createSequentialGroup()
                .addGroup(ReqCorrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReqCorrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ReqCorrPanelLayout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(ReqCorrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30)
                            .addGroup(ReqCorrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ReqCorrCodigoCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ReqCorrEscuelabox, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(ReqCorrPanelLayout.createSequentialGroup()
                            .addGroup(ReqCorrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ReqCorrPanelLayout.createSequentialGroup()
                                    .addGap(98, 98, 98)
                                    .addComponent(jLabel11))
                                .addGroup(ReqCorrPanelLayout.createSequentialGroup()
                                    .addGap(133, 133, 133)
                                    .addGroup(ReqCorrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ReqCorrCodReqbox, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12))))
                            .addGroup(ReqCorrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ReqCorrPanelLayout.createSequentialGroup()
                                    .addGap(88, 88, 88)
                                    .addComponent(jLabel13))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReqCorrPanelLayout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addGroup(ReqCorrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ReqCorrCursoCorrbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(41, 41, 41))))
                        .addGroup(ReqCorrPanelLayout.createSequentialGroup()
                            .addGap(121, 121, 121)
                            .addComponent(RegReqbutton))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReqCorrPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(RegCorrbutton)
                            .addGap(21, 21, 21)))
                    .addGroup(ReqCorrPanelLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(ReqCorr_to_menubutton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ReqCorrPanelLayout.setVerticalGroup(
            ReqCorrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReqCorrPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addGap(40, 40, 40)
                .addGroup(ReqCorrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ReqCorrEscuelabox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ReqCorrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ReqCorrCodigoCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(ReqCorrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ReqCorrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReqCorrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReqCorrCodReqbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReqCorrCursoCorrbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ReqCorrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegReqbutton)
                    .addComponent(RegCorrbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(ReqCorr_to_menubutton)
                .addGap(31, 31, 31))
        );

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setText("Registro de Planes de Estudio");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Escuela/Área propietaria del plan:");

        PlanEscuelabox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Vigencia del plan estudios:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Código del plan estudios:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Código del curso que forma parte del plan:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Bloque:");

        PlanSemestrebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        PlanRegbutton.setText("Registrar curso al plan de estudios");
        PlanRegbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlanRegbuttonActionPerformed(evt);
            }
        });

        Planes_to_menubutton.setText("volver");
        Planes_to_menubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Planes_to_menubuttonActionPerformed(evt);
            }
        });

        PlanDiabox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        PlanAnnobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        PlanMesbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout PlanEstudioPanelLayout = new javax.swing.GroupLayout(PlanEstudioPanel);
        PlanEstudioPanel.setLayout(PlanEstudioPanelLayout);
        PlanEstudioPanelLayout.setHorizontalGroup(
            PlanEstudioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlanEstudioPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(PlanEstudioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PlanEstudioPanelLayout.createSequentialGroup()
                        .addGroup(PlanEstudioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(PlanEstudioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PlanEscuelabox, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PlanCodigoField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PlanEstudioPanelLayout.createSequentialGroup()
                                .addComponent(PlanDiabox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PlanMesbox, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PlanAnnobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PlanEstudioPanelLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(137, 137, 137)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 129, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlanEstudioPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PlanEstudioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlanEstudioPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlanEstudioPanelLayout.createSequentialGroup()
                        .addComponent(PlanRegbutton)
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlanEstudioPanelLayout.createSequentialGroup()
                        .addComponent(Planes_to_menubutton)
                        .addGap(28, 28, 28))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlanEstudioPanelLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(PlanCursoField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PlanSemestrebox, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        PlanEstudioPanelLayout.setVerticalGroup(
            PlanEstudioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlanEstudioPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(PlanEstudioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(PlanEscuelabox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PlanEstudioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlanCodigoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(PlanEstudioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(PlanDiabox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlanAnnobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlanMesbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(PlanEstudioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PlanEstudioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlanCursoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlanSemestrebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(PlanRegbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Planes_to_menubutton)
                .addGap(21, 21, 21))
        );

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel21.setText("Generar PDF");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Plan de Estudio:");

        PDFPlanbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        GenPDFbutton.setText("Generar PDF");
        GenPDFbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenPDFbuttonActionPerformed(evt);
            }
        });

        PDF_to_menubutton.setText("volver");
        PDF_to_menubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDF_to_menubuttonActionPerformed(evt);
            }
        });

        Correobutton.setText("Enviar por correo");
        Correobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreobuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PDFPanelLayout = new javax.swing.GroupLayout(PDFPanel);
        PDFPanel.setLayout(PDFPanelLayout);
        PDFPanelLayout.setHorizontalGroup(
            PDFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDFPanelLayout.createSequentialGroup()
                .addGroup(PDFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PDFPanelLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel21))
                    .addGroup(PDFPanelLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(PDF_to_menubutton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PDFPanelLayout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addGroup(PDFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PDFPanelLayout.createSequentialGroup()
                        .addComponent(GenPDFbutton)
                        .addGap(100, 100, 100)
                        .addComponent(Correobutton))
                    .addGroup(PDFPanelLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(PDFPlanbox, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(133, 133, 133))
        );
        PDFPanelLayout.setVerticalGroup(
            PDFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDFPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(PDFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(PDFPlanbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(149, 149, 149)
                .addGroup(PDFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenPDFbutton)
                    .addComponent(Correobutton))
                .addGap(43, 43, 43)
                .addComponent(PDF_to_menubutton)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(RegEscuelaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(RegCursoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ReqCorrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PlanEstudioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PDFPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(RegEscuelaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(RegCursoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ReqCorrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PlanEstudioPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PDFPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegEscuelaMenubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegEscuelaMenubuttonActionPerformed
        // TODO add your handling code here:
        menu_to_Escuela();
    }//GEN-LAST:event_RegEscuelaMenubuttonActionPerformed

    private void RegCursoMenubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegCursoMenubuttonActionPerformed
        // TODO add your handling code here:
        menu_to_Curso();
    }//GEN-LAST:event_RegCursoMenubuttonActionPerformed

    private void ReqCorrMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReqCorrMenuButtonActionPerformed
        // TODO add your handling code here:
        menu_to_reqcorr();
    }//GEN-LAST:event_ReqCorrMenuButtonActionPerformed

    private void CreatePlanMenubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePlanMenubuttonActionPerformed
        // TODO add your handling code here:
        menu_to_PlanEstudio();
    }//GEN-LAST:event_CreatePlanMenubuttonActionPerformed

    private void PDFMenubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDFMenubuttonActionPerformed
        // TODO add your handling code here:
        menu_to_PDF();
        //Crear un pdf con la informacion de las escuelas, cursos, requisitos y correquisitos
       
        


    }//GEN-LAST:event_PDFMenubuttonActionPerformed

    private void RegistrarEscuelabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarEscuelabuttonActionPerformed
        
        //Revisar si los campos estan vacios mostrar un joptionpane
        if(NombreField.getText().isEmpty() || CodigoField.getText().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Los campos no pueden estar vacios", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        //Revisar si ya existe el codigo
        else if(escuelaController.getEscuelasArea().stream().anyMatch((escuela) -> escuela.getCode().equals(CodigoField.getText()))){
            javax.swing.JOptionPane.showMessageDialog(this, "Ya existe una escuela o area con ese codigo", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        //revisar que el codigo sea de 2 letras
        }else if(CodigoField.getText().length() != 2){
            javax.swing.JOptionPane.showMessageDialog(this, "El código debe ser de 2 caracteres", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        //revisar que el codigo sea solo letras
        }else if(!CodigoField.getText().matches("[a-zA-Z]+")){
            javax.swing.JOptionPane.showMessageDialog(this, "El código debe ser solo letras", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        }else{
            //Crear una nueva escuela
            escuelaController.addEscuelaArea(new EscuelaArea(NombreField.getText(), CodigoField.getText()));
            javax.swing.JOptionPane.showMessageDialog(this, "Escuela o Area registrada con exito");
            //Limpiar los campos
            NombreField.setText("");
            CodigoField.setText("");

            Escuela_to_menu();

        }
    }//GEN-LAST:event_RegistrarEscuelabuttonActionPerformed

    private void LimpiarEscuelabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarEscuelabuttonActionPerformed
        // TODO add your handling code here:
        NombreField.setText("");
        CodigoField.setText("");
    }//GEN-LAST:event_LimpiarEscuelabuttonActionPerformed

    private void Escuela_to_menubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Escuela_to_menubuttonActionPerformed
        // TODO add your handling code here:
        Escuela_to_menu();
    }//GEN-LAST:event_Escuela_to_menubuttonActionPerformed

    private void NombreCursoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreCursoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreCursoFieldActionPerformed

    private void RegCursoEscuelaboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RegCursoEscuelaboxItemStateChanged
        // TODO add your handling code here:
        //set RegCursoEscuelaCodigoLabel to the code of the selected escuela
        int index = RegCursoEscuelabox.getSelectedIndex();
        if (index == -1) return;
        else{
            RegCursoEscuelaCodigoLabel.setText(escuelaController.getEscuelasArea().get(index).getCode());
        }
    }//GEN-LAST:event_RegCursoEscuelaboxItemStateChanged

    private void RegisterCursobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterCursobuttonActionPerformed
        // TODO add your handling code here:
        //Revisar si los campos estan vacios mostrar un joptionpane
        if(NombreCursoField.getText().isEmpty() || RegCursoCodField.getText().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Los campos no pueden estar vacios", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        //check codigo es de 6 caracteres y es unico
        else if(RegCursoCodField.getText().length() != 4){
            javax.swing.JOptionPane.showMessageDialog(this, "El código debe ser de 4 caracteres", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        //revisar que el codigo sea solo numeros
        else if(!RegCursoCodField.getText().matches("[0-9]+")){
            javax.swing.JOptionPane.showMessageDialog(this, "El código debe ser solo numeros", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        else if(cursoController.getCursos().stream().anyMatch((curso) -> Integer.toString(curso.getCode()).equals(RegCursoCodField.getText())  && curso.getEscArea().getCode().equals(escuelaController.getEscuelasArea().get(RegCursoEscuelabox.getSelectedIndex()).getCode()))){
            javax.swing.JOptionPane.showMessageDialog(this, "Ya existe un curso con ese codigo", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        else{
            //Crear un nuevo curso
            Curso curso = new Curso(escuelaController.getEscuelasArea().get(RegCursoEscuelabox.getSelectedIndex()), NombreCursoField.getText(), Integer.parseInt(RegCursoCodField.getText()), Integer.parseInt(RegCursoCredbox.getSelectedItem().toString()), Integer.parseInt(RegCursoHorasbox.getSelectedItem().toString()));
            cursoController.addCurso(curso);
            javax.swing.JOptionPane.showMessageDialog(this, "Curso registrado con exito");
            //Limpiar los campos
            NombreCursoField.setText("");
            RegCursoCodField.setText("");

            //print curso data
            System.out.println("Curso: " + curso.getName() + " Codigo: " + curso.getCode() + " Creditos: " + curso.getCreditos() + " Horas: " + curso.getHorasLectivas() + " Escuela: " + curso.getEscArea().getName());

            Curso_to_menu();
        }
    }//GEN-LAST:event_RegisterCursobuttonActionPerformed

    private void LimpiarCursosbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarCursosbuttonActionPerformed
        // TODO add your handling code here:
        NombreCursoField.setText("");
        RegCursoCodField.setText("");
    }//GEN-LAST:event_LimpiarCursosbuttonActionPerformed

    private void Cursos_to_MenubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cursos_to_MenubuttonActionPerformed
        // TODO add your handling code here:
        Curso_to_menu();
    }//GEN-LAST:event_Cursos_to_MenubuttonActionPerformed

    private void ReqCorrEscuelaboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ReqCorrEscuelaboxItemStateChanged
        // TODO add your handling code here:
        //print the selected escuela index
        int index = ReqCorrEscuelabox.getSelectedIndex();
        System.out.println(index);
        if (index == -1) return;
        else{
            update_req_corr();
        }
        
    }//GEN-LAST:event_ReqCorrEscuelaboxItemStateChanged

    private void RegCorrbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegCorrbuttonActionPerformed
        //add requisito to curso
        Curso cursocorr = cursoController.getCursos().get(ReqCorrCursoCorrbox.getSelectedIndex());
        //get selected curso from escuela codigobox
        EscuelaArea escuela = escuelaController.getEscuelasArea().get(ReqCorrEscuelabox.getSelectedIndex());
        List<Curso> cursosEscuela = cursoController.getCursosByEscuela(escuela.getName());
        

        cursosEscuela.get(ReqCorrCodigoCbox.getSelectedIndex()).addCorrequisito(cursocorr);
        javax.swing.JOptionPane.showMessageDialog(this, "Correquisito registrado con exito");

    }//GEN-LAST:event_RegCorrbuttonActionPerformed

    private void RegReqbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegReqbuttonActionPerformed
        // TODO add your handling code here:
        
        //add requisito to curso
        Curso cursoReq = cursoController.getCursos().get(ReqCorrCodReqbox.getSelectedIndex());
        //get selected curso from escuela codigobox
        EscuelaArea escuela = escuelaController.getEscuelasArea().get(ReqCorrEscuelabox.getSelectedIndex());
        List<Curso> cursosEscuela = cursoController.getCursosByEscuela(escuela.getName());
        

        cursosEscuela.get(ReqCorrCodigoCbox.getSelectedIndex()).addRequisito(cursoReq);
        javax.swing.JOptionPane.showMessageDialog(this, "Requisito registrado con exito");

    }//GEN-LAST:event_RegReqbuttonActionPerformed

    private void ReqCorr_to_menubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReqCorr_to_menubuttonActionPerformed
        // TODO add your handling code here:
        ReqCorr_to_menu();
    }//GEN-LAST:event_ReqCorr_to_menubuttonActionPerformed

    private void PlanRegbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlanRegbuttonActionPerformed
        // TODO add your handling code here:
        

        //Revisar si los campos estan vacios mostrar un joptionpane
        if(PlanCodigoField.getText().isEmpty() || PlanCursoField.getText().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Los campos no pueden estar vacios", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        //revisar que la fecha sea valida
        else if(Integer.parseInt(PlanDiabox.getSelectedItem().toString()) < 1 || Integer.parseInt(PlanDiabox.getSelectedItem().toString()) > 31 || Integer.parseInt(PlanMesbox.getSelectedItem().toString()) < 1 || Integer.parseInt(PlanMesbox.getSelectedItem().toString()) > 12 || Integer.parseInt(PlanAnnobox.getSelectedItem().toString()) < 2000 || Integer.parseInt(PlanAnnobox.getSelectedItem().toString()) > 2030){
            javax.swing.JOptionPane.showMessageDialog(this, "Fecha no valida", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        //revisar febrero
        else if(Integer.parseInt(PlanDiabox.getSelectedItem().toString()) > 29 && Integer.parseInt(PlanMesbox.getSelectedItem().toString()) == 2){
            javax.swing.JOptionPane.showMessageDialog(this, "Fecha no valida", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        //revisar codigo de curso valido
        else if(cursoController.getCursos().stream().noneMatch((curso) -> (curso.getEscArea().getCode()+curso.getCode()).equals(PlanCursoField.getText()))){
            javax.swing.JOptionPane.showMessageDialog(this, "No existe un curso con ese codigo", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        
        //codigo de plan debe ser 4 numeros
        else if(PlanCodigoField.getText().length() != 4){
            javax.swing.JOptionPane.showMessageDialog(this, "El código debe ser de 4 números", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        //revisar que el codigo sea solo numeros
        else if(!PlanCodigoField.getText().matches("[0-9]+")){
            javax.swing.JOptionPane.showMessageDialog(this, "El código debe ser solo numeros", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        else{
            //Crear un nuevo plan de estudio
            create_plan();

        }
    }//GEN-LAST:event_PlanRegbuttonActionPerformed

    private void Planes_to_menubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Planes_to_menubuttonActionPerformed
        // TODO add your handling code here:
        PlanEstudio_to_menu();
        
    }//GEN-LAST:event_Planes_to_menubuttonActionPerformed

    private void PDF_to_menubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDF_to_menubuttonActionPerformed
        // TODO add your handling code here:
        PDF_to_menu();
    }//GEN-LAST:event_PDF_to_menubuttonActionPerformed

    private void GenPDFbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenPDFbuttonActionPerformed
        // TODO add your handling code here:

        //get selected plan
        PlanEstudios plan = planEstudioController.getPlanEstudios().get(PDFPlanbox.getSelectedIndex());
        //get path
        if(path == null){
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un path", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        else{
            //create pdf
     

            PDFCreator pdfCreator = new PDFCreator();
            String fullpath = path + plan.getEscArea().getCode() +Integer.toString(plan.getCode())+".pdf";
            pdfCreator.createPDF(fullpath, plan);
            javax.swing.JOptionPane.showMessageDialog(this, "PDF generado con exito");
            
           
        }

    }//GEN-LAST:event_GenPDFbuttonActionPerformed

    private void CorreobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreobuttonActionPerformed
        // TODO add your handling code here:
        //open joptionpane to input email
        String email = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el correo electronico", "Correo", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        PlanEstudios plan = planEstudioController.getPlanEstudios().get(PDFPlanbox.getSelectedIndex());
        EmailSender emailSender = new EmailSender();

        //check if pdf has been created by checking if the fil
        try{
            String fullpath = path + plan.getEscArea().getCode() +Integer.toString(plan.getCode())+".pdf";
            File fpdf = new File(fullpath);
            if (!email.isEmpty()) {
            emailSender.emailSend(email, "Reciba un saludo, estimad@ usuari@, este es el plan de estudio", fpdf);
            javax.swing.JOptionPane.showMessageDialog(this, "Correo enviado con exito");
            } else {
            javax.swing.JOptionPane.showMessageDialog(this, "El campo de correo está vacío", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        }catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(this, "No se ha generado un PDF", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        

    }//GEN-LAST:event_CorreobuttonActionPerformed
    
    
    
    
    private void menu_to_Escuela(){
        RegEscuelaPanel.setVisible(true);
        MenuPanel.setVisible(false);
    }
    
    private void Escuela_to_menu(){
        RegEscuelaPanel.setVisible(false);
        MenuPanel.setVisible(true);
    }

    private void menu_to_Curso(){
        RegCursoPanel.setVisible(true);
        MenuPanel.setVisible(false);

        //set list of escuelas to RegCursoEscuelabox
        RegCursoEscuelabox.removeAllItems();
        if (!escuelaController.getEscuelasArea().isEmpty()) {
            escuelaController.getEscuelasArea().forEach((escuela) -> {
            RegCursoEscuelabox.addItem(escuela.getName());
            });
            //set RegCursoEscuelaCodigoLabel to the code of the first escuela
            RegCursoEscuelaCodigoLabel.setText(escuelaController.getEscuelasArea().get(0).getCode());

            //set RegCursoEscuelabox selected index to 0
            RegCursoEscuelabox.setSelectedIndex(0);
        }

        //set list of creditos to RegCursoCredbox from 0 to 4
        RegCursoCredbox.removeAllItems();
        for(int i = 0; i < 5; i++){
            RegCursoCredbox.addItem(Integer.toString(i));
        }

        //set list of horas to RegCursoHorasbox from 1 to 5
        RegCursoHorasbox.removeAllItems();
        for(int i = 1; i < 6; i++){
            RegCursoHorasbox.addItem(Integer.toString(i));
        }
        
    }

    private void Curso_to_menu(){
        RegCursoPanel.setVisible(false);
        MenuPanel.setVisible(true);
    }


    private void update_req_corr(){
        
        //set ReqCorrCodigoCbox to the cursos of the selected escuela
        ReqCorrCodigoCbox.removeAllItems();
        EscuelaArea selectedEscuela = escuelaController.getEscuelasArea().get(ReqCorrEscuelabox.getSelectedIndex());
        List<Curso> cursos = cursoController.getCursosByEscuela(selectedEscuela.getName());
        cursos.forEach((curso) -> {
            ReqCorrCodigoCbox.addItem(selectedEscuela.getCode()+Integer.toString(curso.getCode()));
        });

    }

    private void menu_to_reqcorr(){
        ReqCorrPanel.setVisible(true);
        MenuPanel.setVisible(false);
        
        ReqCorrEscuelabox.removeAllItems();
        escuelaController.getEscuelasArea().forEach((escuela) -> {
            ReqCorrEscuelabox.addItem(escuela.getName());
        });
        ReqCorrEscuelabox.setSelectedIndex(0);


        update_req_corr();

        //set ReqCorrCodReqbox to the cursos
        ReqCorrCodReqbox.removeAllItems();
        //go through all cursos
        cursoController.getCursos().forEach((curso) -> {
            ReqCorrCodReqbox.addItem(curso.getEscArea().getCode()+Integer.toString(curso.getCode()));
        });

        //set ReqCorrCursoCorrbox to the cursos
        ReqCorrCursoCorrbox.removeAllItems();
        //go through all cursos
        cursoController.getCursos().forEach((curso) -> {
            ReqCorrCursoCorrbox.addItem(curso.getEscArea().getCode()+Integer.toString(curso.getCode()));
        });
    }

    private void ReqCorr_to_menu(){
        ReqCorrPanel.setVisible(false);
        MenuPanel.setVisible(true);
    }
    
    private void PlanEstudio_to_menu(){
        PlanEstudioPanel.setVisible(false);
        MenuPanel.setVisible(true);

        

    }

    private void menu_to_PlanEstudio(){
        PlanEstudioPanel.setVisible(true);
        MenuPanel.setVisible(false);
        //set PlanEscuelabox to the escuelas
        PlanEscuelabox.removeAllItems();
        escuelaController.getEscuelasArea().forEach((escuela) -> {
            PlanEscuelabox.addItem(escuela.getName());
        });

        //set PlanDiabox to the dias
        PlanDiabox.removeAllItems();
        for(int i = 1; i < 32; i++){
            PlanDiabox.addItem(Integer.toString(i));
        }

        //set PlanMesbox to the meses
        PlanMesbox.removeAllItems();
        for(int i = 1; i < 13; i++){
            PlanMesbox.addItem(Integer.toString(i));
        }

        //set PlanAnnobox to the años
        PlanAnnobox.removeAllItems();
        for(int i = 2000; i < 2031; i++){
            PlanAnnobox.addItem(Integer.toString(i));
        }

        //set PlanSemestrebox to the semestres with the following format: "l Semestre", "ll Semestre" until "Xl Semestre" 
        PlanSemestrebox.removeAllItems();
        for(int i = 1; i < 11; i++){
            PlanSemestrebox.addItem( toRoman(i) + " Semestre");
        }
    }

    private void menu_to_PDF(){
        PDFPanel.setVisible(true);
        MenuPanel.setVisible(false);

        //set PDFPlanbox to the planes de estudio
        PDFPlanbox.removeAllItems();
        planEstudioController.getPlanEstudios().forEach((plan) -> {
            PDFPlanbox.addItem(plan.getEscArea().getName() + Integer.toString(plan.getCode()));
        });

    }

    private void PDF_to_menu(){
        PDFPanel.setVisible(false);
        MenuPanel.setVisible(true);
    }


    //function to turn numbers into roman numerals
    private String toRoman(int number){
        String roman = "";
        while(number >= 1000){
            roman += "M";
            number -= 1000;
        }
        while(number >= 900){
            roman += "CM";
            number -= 900;
        }
        while(number >= 500){
            roman += "D";
            number -= 500;
        }
        while(number >= 400){
            roman += "CD";
            number -= 400;
        }
        while(number >= 100){
            roman += "C";
            number -= 100;
        }
        while(number >= 90){
            roman += "XC";
            number -= 90;
        }
        while(number >= 50){
            roman += "L";
            number -= 50;
        }
        while(number >= 40){
            roman += "XL";
            number -= 40;
        }
        while(number >= 10){
            roman += "X";
            number -= 10;
        }
        while(number >= 9){
            roman += "IX";
            number -= 9;
        }
        while(number >= 5){
            roman += "V";
            number -= 5;
        }
        while(number >= 4){
            roman += "IV";
            number -= 4;
        }
        while(number >= 1){
            roman += "I";
            number -= 1;
        }
        return roman;
    }

    private void create_plan(){
        
        EscuelaArea escuela = escuelaController.getEscuelasArea().get(PlanEscuelabox.getSelectedIndex());
        //System.out.println(escuela.getName());

        List<Curso> cursosEscuela = cursoController.getCursos();
        
        Curso curso = cursosEscuela.stream().filter((c) -> (c.getEscArea().getCode()+c.getCode()).equals(PlanCursoField.getText())).findFirst().get();
        //System.out.println(curso.getName());

        int code = Integer.parseInt(PlanCodigoField.getText());
        //System.out.println(code);

        String fecha = PlanDiabox.getSelectedItem().toString() + "/" + PlanMesbox.getSelectedItem().toString() + "/" + PlanAnnobox.getSelectedItem().toString();
        //System.out.println(fecha);

        String semestre = PlanSemestrebox.getSelectedItem().toString();
        //System.out.println(semestre);
        
        
        //check if plan already exists
        if(planEstudioController.getPlanEstudios().stream().anyMatch((plan) -> (plan.getEscArea().getCode() + plan.getCode()).equals(escuela.getCode()+code))){
            PlanEstudios planold = planEstudioController.getPlanEstudios().stream().filter((plan) -> (plan.getEscArea().getCode() + plan.getCode()).equals(escuela.getCode()+code)).findFirst().get();
            
           
            //check if curso already exists
            if(planold.getCursos().stream().anyMatch((c) -> c.equals(curso))){
                javax.swing.JOptionPane.showMessageDialog(this, "El curso ya esta registrado en el plan de estudios", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            else{
                planold.addCurso(curso);

                //check if semestre already exists
                if(planold.getBloques().stream().anyMatch((bloque) -> bloque.equals(semestre))){
                    planold.asociarCursoABloque(curso, semestre);

                }else{

                    planold.addBloque(semestre);
                    planold.asociarCursoABloque(curso, semestre);
                }

            }
            

           
        }
        else{
            PlanEstudios plannew = new PlanEstudios(escuela, code, fecha);
            plannew.addCurso(curso);
            plannew.addBloque(semestre);
            plannew.asociarCursoABloque(curso, semestre);
            planEstudioController.addPlanEstudio(plannew);
           
        }

        javax.swing.JOptionPane.showMessageDialog(this, "Curso registrado en plan de estudios con exito");
        
        
    }



    //Variables Globals
    
    public EscuelaAreaController escuelaController = new EscuelaAreaController();
    public CursoController cursoController = new CursoController();
    public PlanEstudiosController planEstudioController = new PlanEstudiosController();
    String path = "PDFs/";
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUI gui = new GUI();
            //make it not resizable
                gui.setResizable(false);
                gui.setVisible(true);
                gui.RegEscuelaPanel.setVisible(false);
                gui.RegCursoPanel.setVisible(false);
                gui.ReqCorrPanel.setVisible(false);
                gui.PlanEstudioPanel.setVisible(false);
                gui.PDFPanel.setVisible(false);
                
                
                
                //generate some data for test
                EscuelaArea escuela1 = new EscuelaArea("Escuela de Ingenieria", "EI");
                EscuelaArea escuela2 = new EscuelaArea("Escuela de Ciencias", "EC");

                Curso curso1 = new Curso(escuela1, "Calculo I", 1011, 4, 4);
                Curso curso2 = new Curso(escuela1, "Calculo II", 1021, 4, 4);

                Curso curso3 = new Curso(escuela2, "Fisica I", 2011, 4, 4);
                Curso curso4 = new Curso(escuela2, "Fisica II", 2021, 4, 4);

                Curso curso5 = new Curso(escuela1, "Algebra Lineal", 1031, 4, 4);
                Curso curso6 = new Curso(escuela1, "Calculo III", 1041, 4, 4);
                
                gui.escuelaController.addEscuelaArea(escuela1);
                gui.escuelaController.addEscuelaArea(escuela2);

                gui.cursoController.addCurso(curso1);
                gui.cursoController.addCurso(curso2);
                gui.cursoController.addCurso(curso3);
                gui.cursoController.addCurso(curso4);
                gui.cursoController.addCurso(curso5);
                gui.cursoController.addCurso(curso6);
                


            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodigoField;
    private javax.swing.JButton Correobutton;
    private javax.swing.JButton CreatePlanMenubutton;
    private javax.swing.JButton Cursos_to_Menubutton;
    private javax.swing.JButton Escuela_to_menubutton;
    private javax.swing.JButton GenPDFbutton;
    private javax.swing.JButton LimpiarCursosbutton;
    private javax.swing.JButton LimpiarEscuelabutton;
    private javax.swing.JLabel MenuLabel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JTextField NombreCursoField;
    private javax.swing.JTextField NombreField;
    private javax.swing.JButton PDFMenubutton;
    private javax.swing.JPanel PDFPanel;
    private javax.swing.JComboBox<String> PDFPlanbox;
    private javax.swing.JButton PDF_to_menubutton;
    private javax.swing.JComboBox<String> PlanAnnobox;
    private javax.swing.JTextField PlanCodigoField;
    private javax.swing.JTextField PlanCursoField;
    private javax.swing.JComboBox<String> PlanDiabox;
    private javax.swing.JComboBox<String> PlanEscuelabox;
    private javax.swing.JPanel PlanEstudioPanel;
    private javax.swing.JComboBox<String> PlanMesbox;
    private javax.swing.JButton PlanRegbutton;
    private javax.swing.JComboBox<String> PlanSemestrebox;
    private javax.swing.JButton Planes_to_menubutton;
    private javax.swing.JButton RegCorrbutton;
    private javax.swing.JTextField RegCursoCodField;
    private javax.swing.JComboBox<String> RegCursoCredbox;
    private javax.swing.JLabel RegCursoEscuelaCodigoLabel;
    private javax.swing.JComboBox<String> RegCursoEscuelabox;
    private javax.swing.JComboBox<String> RegCursoHorasbox;
    private javax.swing.JButton RegCursoMenubutton;
    private javax.swing.JPanel RegCursoPanel;
    private javax.swing.JLabel RegCursosLabel;
    private javax.swing.JLabel RegEscuelaLabel;
    private javax.swing.JButton RegEscuelaMenubutton;
    private javax.swing.JPanel RegEscuelaPanel;
    private javax.swing.JButton RegReqbutton;
    private javax.swing.JButton RegisterCursobutton;
    private javax.swing.JButton RegistrarEscuelabutton;
    private javax.swing.JComboBox<String> ReqCorrCodReqbox;
    private javax.swing.JComboBox<String> ReqCorrCodigoCbox;
    private javax.swing.JComboBox<String> ReqCorrCursoCorrbox;
    private javax.swing.JComboBox<String> ReqCorrEscuelabox;
    private javax.swing.JButton ReqCorrMenuButton;
    private javax.swing.JPanel ReqCorrPanel;
    private javax.swing.JButton ReqCorr_to_menubutton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
